inherit_from: .rubocop_todo.yml


AllCops:
  NewCops: enable
  Includes:
    - '**/*.rb'
    - Rakefile
    - config.ru
  Excludes:
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/swagger_helper.rb
    - db/**
    - config/**
    - script/**
    - vendor/**/* # Circle adds the rubies here