---
openapi: 3.0.1
info:
  title: API V2
  version: v2
  description: This is the second version of my API
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
